spring:
  profiles: common

tencent:
  cloud:
    appId: 腾讯云APPID
    secretId: 腾讯云SecretId
    secretKey: 腾讯云SecretKey
    region-public: 公有存储桶所在地域
    bucket-public: 公有存储桶名称
    region-private: 私有存储桶所在地域
    bucket-private: 私有存储桶名称

wx:
  app-id: 你的小程序APPID
  app-secret: 你的小程序密钥
  mch-id: 商户号ID（课程QQ群共享里能找到）
  key: 商户密钥（课程QQ群共享里能找到）
  cert-path: 数字证书文件路径（课程QQ群共享里能找到）

minio:
  endpoint: http://localhost:9000
  access-key: root
  secret-key: abc123456
